sudo: required
services:
  - docker

before_install:
  - docker build -t x78240/react-test -f ./client/Dockerfile.dev ./client

script: 
 - docker run -e CI=true x78240/react-test npm test

after_success:
  - docker build -t x78240/multi-client ./client
  - docker build -t x78240/multi-nginx ./nginx
  - docker build -t x78240/multi-server ./server
  - docker build -t x78240/multi-worker ./worker
    
#login to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push to docker hub
  - docker push x78240/multi-client
  - docker push x78240/multi-nginx
  - docker push x78240/multi-server
  - docker push x78240/multi-worker
  
  # Deploy
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-009132788694'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  #fake code to start rebuild